export const CREATE_FOOD_ITEM_REQUEST = 'CREATE_FOOD_ITEM_REQUEST';
export const CREATE_FOOD_ITEM_SUCCESS = 'CREATE_FOOD_ITEM_SUCCESS';
export const CREATE_FOOD_ITEM_FAILURE = 'CREATE_FOOD_ITEM_FAILURE';

export const GET_FOOD_ITEMS_BY_RESTAURANT_ID_REQUEST =
  'GET_FOOD_ITEMS_BY_RESTAURANT_ID_REQUEST';
export const GET_FOOD_ITEMS_BY_RESTAURANT_ID_SUCCESS =
  'GET_FOOD_ITEMS_BY_RESTAURANT_ID_SUCCESS';
export const GET_FOOD_ITEMS_BY_RESTAURANT_ID_FAILURE =
  'GET_FOOD_ITEMS_BY_RESTAURANT_ID_FAILURE';

export const DELETE_FOOD_ITEM_REQUEST = 'DELETE_FOOD_ITEM_REQUEST';
export const DELETE_FOOD_ITEM_SUCCESS = 'DELETE_FOOD_ITEM_SUCCESS';
export const DELETE_FOOD_ITEM_FAILURE = 'DELETE_FOOD_ITEM_FAILURE';

export const SEARCH_FOOD_ITEM_REQUEST = 'SEARCH_FOOD_ITEM_REQUEST';
export const SEARCH_FOOD_ITEM_SUCCESS = 'SEARCH_FOOD_ITEM_SUCCESS';
export const SEARCH_FOOD_ITEM_FAILURE = 'SEARCH_FOOD_ITEM_FAILURE';

export const UPDATE_FOOD_ITEMS_AVAILABILITY_REQUEST = 'UPDATE_FOOD_ITEMS_AVAILABILITY_REQUEST';
export const UPDATE_FOOD_ITEMS_AVAILABILITY_SUCCESS = 'UPDATE_FOOD_ITEMS_AVAILABILITY_SUCCESS';
export const UPDATE_FOOD_ITEMS_AVAILABILITY_FAILURE = 'UPDATE_FOOD_ITEMS_AVAILABILITY_FAILURE';